name: Unit tests

on: [push, pull_request]

jobs:
  run:
    runs-on: 'ubuntu-20.04'
    continue-on-error: true
    strategy:
      matrix:
        include:
          - php-version: '5.6'
            laravel-version: '5.0'
          - php-version: '5.6'
            laravel-version: '5.1'
          - php-version: '5.6'
            laravel-version: '5.2'
          - php-version: '5.6'
            laravel-version: '5.3'
          - php-version: '5.6'
            laravel-version: '5.4'
          - php-version: '7.0'
            laravel-version: '5.0'
          - php-version: '7.0'
            laravel-version: '5.1'
          - php-version: '7.0'
            laravel-version: '5.2'
          - php-version: '7.0'
            laravel-version: '5.3'
          - php-version: '7.0'
            laravel-version: '5.4'
          - php-version: '7.0'
            laravel-version: '5.5'
          - php-version: '7.1'
            laravel-version: '5.0'
          - php-version: '7.1'
            laravel-version: '5.1'
          - php-version: '7.1'
            laravel-version: '5.2'
          - php-version: '7.1'
            laravel-version: '5.3'
          - php-version: '7.1'
            laravel-version: '5.4'
          - php-version: '7.1'
            laravel-version: '5.5'
          - php-version: '7.1'
            laravel-version: '5.6'
          - php-version: '7.1'
            laravel-version: '5.7'
          - php-version: '7.1'
            laravel-version: '5.8'
          - php-version: '7.2'
            laravel-version: '5.0'
          - php-version: '7.2'
            laravel-version: '5.1'
          - php-version: '7.2'
            laravel-version: '5.2'
          - php-version: '7.2'
            laravel-version: '5.3'
          - php-version: '7.2'
            laravel-version: '5.4'
          - php-version: '7.2'
            laravel-version: '5.5'
          - php-version: '7.2'
            laravel-version: '5.6'
          - php-version: '7.2'
            laravel-version: '5.7'
          - php-version: '7.2'
            laravel-version: '5.8'
          - php-version: '7.2'
            laravel-version: '6'
          - php-version: '7.2'
            laravel-version: '7.0'
          - php-version: '7.3'
            laravel-version: '5.0'
          - php-version: '7.3'
            laravel-version: '5.1'
          - php-version: '7.3'
            laravel-version: '5.2'
          - php-version: '7.3'
            laravel-version: '5.3'
          - php-version: '7.3'
            laravel-version: '5.4'
          - php-version: '7.3'
            laravel-version: '5.5'
          - php-version: '7.3'
            laravel-version: '5.6'
          - php-version: '7.3'
            laravel-version: '5.7'
          - php-version: '7.3'
            laravel-version: '5.8'
          - php-version: '7.3'
            laravel-version: '6'
          - php-version: '7.3'
            laravel-version: '7'
          - php-version: '7.3'
            laravel-version: '8'
          - php-version: '7.4'
            laravel-version: '5.0'
          - php-version: '7.4'
            laravel-version: '5.1'
          - php-version: '7.4'
            laravel-version: '5.2'
          - php-version: '7.4'
            laravel-version: '5.3'
          - php-version: '7.4'
            laravel-version: '5.4'
          - php-version: '7.4'
            laravel-version: '5.5'
          - php-version: '7.4'
            laravel-version: '5.6'
          - php-version: '7.4'
            laravel-version: '5.7'
          - php-version: '7.4'
            laravel-version: '5.8'
          - php-version: '7.4'
            laravel-version: '6'
          - php-version: '7.4'
            laravel-version: '7'
          - php-version: '7.4'
            laravel-version: '8'
          - php-version: '8.0'
            laravel-version: '7'
          - php-version: '8.0'
            laravel-version: '8'

    name: Testing Laravel ${{ matrix.laravel-version }} with PHP ${{ matrix.php-version }}

    steps:
      - uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-version }}

      - uses: actions/checkout@v2

      - run: composer validate
      - run: composer require --with-all-dependencies illuminate/console=${{ matrix.laravel-version }}.* illuminate/events=${{ matrix.laravel-version }}.* illuminate/support=${{ matrix.laravel-version }}.*
      - run: vendor/bin/phpunit
      - run: composer update --no-interaction --prefer-lowest
      - run: vendor/bin/phpunit
